//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace solution_EDGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle
    {
        public int id { get; set; }
        public Nullable<int> idfactura { get; set; }
        public string descripcionArticulo { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual factura factura { get; set; }
    }
}
