//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace solution_EDGV.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class pago
    {
        public int id { get; set; }

        public Nullable<System.DateTime> fecha { get; set; }
        [Display(Name="Nro Factura")]
        public Nullable<int> idfactura { get; set; }
        public Nullable<decimal> montopago { get; set; }
    
        public virtual factura factura { get; set; }
    }
}
